### ISSUE TITLE
Kissanime HTTPS

### ISSUE THREAD

**Issue by fumetsuu** [Vergo777/Kissanime-LinkDownload#10]
ever since kissanime changed to https://kissanime.to, the script hasn't been working correctly. The numbers are shown but the links aren't shown after that. Any solutions? Thanks.

**Comment by RutgerM** [comment]
@fumetsuu : This is because the script still uses the old domain and for some reason, it won't redirect itself to the new domain.

I have forked the script here, with the new domain: https://github.com/RutgerM/Kissanime-LinkDownload

**Comment by fumetsuu** [comment]
have you tried using the script for the new website? (it has recently changed to https in the last few days), for me it results as an error.

**Comment by RutgerM** [comment]
@fumetsuu: No, I have not, sorry.

I have updated the forked script to use https, so it should work now.

**Comment by fumetsuu** [comment]
hmm, seems I managed to fix it somehow but I'm not too sure how long this will be in effect for

**Comment by fumetsuu** [comment]
I think it works now, thank you very much!

**Comment by dreadbcool4ever** [comment]
@fumetsuu I know this is closed, but if you have any further problems, I updated my script, so that Bitly returns the URL's now. I noticed it only today, and fixed it in the pastebin
