### ISSUE TITLE
CONVERTING_PROCESS

### ISSUE THREAD

**Issue by scooby5691** [Vergo777/Kissanime-LinkDownload#3]
hello
 this is the error i get, is there a solution?

"exception in thread main java.lang.negativearraysizeexception at link.main(link.java36)"

**Comment by Vergo777** [comment]
Hey there @scooby5691, could you provide the contents of your 'links.txt' file so that I can try and reproduce the error on my side?

**Comment by scooby5691** [comment]
good morning sorry that i am only get back to you now, i will do so now, i did all that you shown in the tutorial, but it does not come to the converting part, it kicks me out and closes.

these are the links i want to convert in option 5

http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-025?id=66055
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-024?id=65710
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-023?id=65455
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-022?id=64962
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-021?id=64523
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-020?id=64011
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-019?id=63751
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-018?id=63493
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-017?id=63415
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-016?id=63319
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-015?id=62786
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-014?id=62192
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-013?id=61707
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-012?id=61705
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-011?id=61239
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-010?id=59499
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-009?id=59027
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-008?id=58656
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-007?id=58261
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-006?id=57567
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-005?id=56847
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-004?id=56147
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-003?id=55250
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-002?id=54800
http://kissanime.com/Anime/Hajime-no-Ippo-Rising/Episode-001?id=53691

**Comment by Vergo777** [comment]
Apologies for the delay in getting back to you, it seems that Kissanime have changed things so that you get the download links only if you're logged in. I'll try to make changes and see what I can do to get around that.
