### ISSUE TITLE
All my results are Null

### ISSUE THREAD

**Issue by Darkfard** [Vergo777/Kissanime-LinkDownload#4]
Hi,

I'm currently trying to download an anime series but the results I get in the .txt file are always "null". The video has a costum pixel size, 528x360.mp4 but it's not getting me anything. Is this a bug with the costum quality function?

Thanks!

**Comment by Vergo777** [comment]
Hey there, I just replied to issue https://github.com/Vergo777/Kissanime-LinkDownload/issues/3 describing the same problem. I'll try to figure out a way to work around it.

**Comment by sirius16** [comment]
It's not just custom quality, it's all quality

**Comment by sirius16** [comment]
If it helps, you should know that before when you viewed the source of the kissanime site you could find the download links but now you can't

**Comment by Vergo777** [comment]
@sirius16, yep I noticed that when I was looking over things yesterday. The download links are dynamically generated now so I'll probably change the code to use HtmlUnit instead of Jsoup.

**Comment by Darkfard** [comment]
@Vergo777 Ok thanks for doing this! I'll check back once in a while!

**Comment by Vergo777** [comment]
So I basically gave up on getting it working with HtmlUnit because it was a massive pain in the ass to use, and switched to a Javascript implementation instead. Hopefully having it all in the browser should make life a lot easier. 

@Darkfard, you can give it a go now and see if it works.

**Comment by sirius16** [comment]
OH. MY. GOSH. You did it! It works

**Comment by mysticpoisen** [comment]
While this issue is open, probably the wrong place for this, but when you batch download using IDM, how do you keep the episodes in order, or at least with any kind of reasonable naming convention?

**Comment by sirius16** [comment]
If you use Chrome you can download Chrome Download Manager which lets you number your files

**Comment by zshanif** [comment]
Long time lurker on this. Adding &title= to the video url (the actual url,
not the bit.ly one) names the file. So if you were to add
&title=Episode+1.mp4 to the end of the url, the download would
automatically be renamed to "Episode 1" instead of "videoplayback"

**Comment by Vergo777** [comment]
@zshanif Thanks for pointing that out. Unfortunately the final video link is obtained after redirection from the link on the actual page. So appending a title to the link on the page before passing it through bit.ly doesn't make a difference since it simply disappears after the redirection. 

Having said that, this looks like the best approach to get the naming sorted out so I'll keep it in mind while trying to come up with a solution.

**Comment by Darkfard** [comment]
@Vergo777 Thanks i'll try it once i get home! I hope they won't patch this. Thanks!

**Comment by Darkfard** [comment]
@Vergo777 Just tried it, the links work but I can only manage to get 99 links, tried to get 148 links but it's only returning 99 bit.ly links although the console counted down from 147 to 0. 

It's not a huge problem though, I could generate links 2 times (1-80 & 81-148).

**Comment by sirius16** [comment]
@zshanif In regards to that, with chrome you can download an extension Copy all urls (https://chrome.google.com/webstore/detail/copy-all-urls/djdmadneanknadilpjiknlnanaolmbfk), copy and paste the bit.ly links, copy the new videolinks, and rename them. You can use excel or LibreOffice Calc, to add the &title thing faster.

It seems like a lot, but it's simple and really quick
