### ISSUE TITLE
Script Error Throws (Any Anime)

### ISSUE THREAD

**Issue by dreadbcool4ever** [Vergo777/Kissanime-LinkDownload#7]
Hello.

Love to say, love this script, but I've ran into an error now, with no idea on how to fix it.

I've run the script on several anime, Fairy Tail, Fullmetal Alchemist, Ai Mai Mi, and I get the same error.

1st. It comes out the link as undefined. Only undefined.
2nd. I get only errors like this "GET https://chitika.com/sites/all/themes/chitika/images/bg_metal.gif?aid=479402 504 (GATEWAY_TIMEOUT)"

That's all I get. 

Thanks for taking time to read

Sincerely,
Dread

**Comment by vavavr00m** [comment]
Check instruction # 1. Works for me just fine.

![Fairy Tail](https://dl.dropboxusercontent.com/s/jdzgrtwnewhn1yz/2015-08-30_02-12-54.png)

**Comment by dreadbcool4ever** [comment]
Ok. Thanks for the suggestion, but I'm still new, and since I've been using the script, I have no idea how to use it with my own bitly API key. Any chance you might be able to help me then? I got the API key, just no idea how to use it.
